// This file is auto-generated by CDK at deploy time. These are placeholders.
// Do NOT edit manually — CDK generates the real config.js via frontend_deployment.py
const CONFIG = {
    API_ENDPOINT: 'PLACEHOLDER_API_ENDPOINT',
    COGNITO_DOMAIN: 'PLACEHOLDER_COGNITO_DOMAIN',
    COGNITO_CLIENT_ID: 'PLACEHOLDER_COGNITO_CLIENT_ID',
    COGNITO_REDIRECT_URI: 'PLACEHOLDER_CLOUDFRONT_URL',
    VIDEO_CDN: 'PLACEHOLDER_VIDEO_CDN'
};
