"""CloudFormation custom resource: empty the S3 Vectors bucket before it is deleted.

S3 Vectors refuses to delete a vector bucket that still holds indexes, so a
CfnVectorBucket with RemovalPolicy.DESTROY would fail `cdk destroy` on any stack
that ever created a project. This is the S3 Vectors counterpart to
s3.Bucket(auto_delete_objects=True): on stack delete it removes every index so
the bucket deletion that CloudFormation performs next can succeed.

Deleting an index deletes the vectors inside it. That data is derived — it is
regenerated by re-running the ingestion pipeline over the source videos in the
videos bucket — so it is safe to discard with the stack.

Create and Update are deliberate no-ops: CfnVectorBucket owns the bucket itself,
and per-project indexes are created at runtime by vector_store.create_project_indices().
"""
import os

import boto3
from botocore.exceptions import ClientError

s3vectors = boto3.client('s3vectors', region_name=os.environ.get('AWS_REGION', 'us-east-1'))

# Raised when the bucket is already gone, which is not an error during teardown.
_MISSING = ('NotFoundException', 'ResourceNotFoundException', 'NoSuchBucket')


def lambda_handler(event, context):
    """Entry point for the cr.Provider framework, which expects a returned dict."""
    request_type = event.get('RequestType', '')
    bucket = event['ResourceProperties']['VectorBucketName']

    if request_type == 'Delete':
        count = _delete_all_indexes(bucket)
        print(f"Removed {count} index(es) from vector bucket {bucket}")

    return {
        'PhysicalResourceId': f"vector-bucket-cleanup-{bucket}",
        'Data': {'VectorBucketName': bucket},
    }


def _list_index_names(bucket):
    """Every index name in the bucket, following pagination to the end.

    Listing is completed before any delete so that deleting an index cannot
    invalidate a nextToken mid-walk.
    """
    names, token = [], None
    while True:
        kwargs = {'vectorBucketName': bucket}
        if token:
            kwargs['nextToken'] = token
        resp = s3vectors.list_indexes(**kwargs)
        names.extend(i['indexName'] for i in resp.get('indexes', []))
        token = resp.get('nextToken')
        if not token:
            return names


def _delete_all_indexes(bucket):
    try:
        names = _list_index_names(bucket)
    except ClientError as e:
        if e.response['Error']['Code'] in _MISSING:
            print(f"Vector bucket {bucket} not found — nothing to clean up")
            return 0
        raise

    deleted = 0
    for name in names:
        try:
            s3vectors.delete_index(vectorBucketName=bucket, indexName=name)
            deleted += 1
        except ClientError as e:
            # Already deleted by a project delete racing this teardown.
            if e.response['Error']['Code'] not in _MISSING:
                raise
    return deleted
